{{- if not (lookup "lib.projectsveltos.io/v1beta1" "DebuggingConfiguration" "" "default") }}
apiVersion: lib.projectsveltos.io/v1beta1
kind: DebuggingConfiguration
metadata:
  name: default
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
spec:
  configuration:
  - component: AccessManager
    logLevel: LogLevelInfo
  - component: AddonManager
    logLevel: LogLevelInfo
  - component: Classifier
    logLevel: LogLevelInfo
  - component: DriftDetectionManager
    logLevel: LogLevelInfo
  - component: EventManager
    logLevel: LogLevelInfo
  - component: HealthCheckManager
    logLevel: LogLevelInfo
  - component: SveltosClusterManager
    logLevel: LogLevelInfo
  - component: UIBackend
    logLevel: LogLevelInfo
  - component: SveltosAgent
    logLevel: LogLevelInfo
  - component: ShardController
    logLevel: LogLevelInfo
  - component: ConversionWebhook
    logLevel: LogLevelInfo
  - component: Techsupport
    logLevel: LogLevelInfo
{{- end }}