---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterTemplate
metadata:
  name: hetzner-standalone-cp-1-0-0
  namespace: {{ .Values.config.namespace | default .Release.Namespace | trunc 63 }}
spec:
  helm:
    chartSpec:
      chart: hetzner-standalone-cp
      version: 1.0.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: oot-repo
