---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ProviderTemplate
metadata:
  name: cluster-api-provider-hetzner-1-0-0
spec:
  helm:
    chartSpec:
      chart: cluster-api-provider-hetzner
      version: 1.0.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: oot-repo
