apiVersion: v1
kind: ServiceAccount
metadata:
  name: addon-controller
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.addonController.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: access-manager
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.accessManager.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sc-manager
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.scManager.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hc-manager
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.hcManager.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-manager
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.eventManager.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: classifier-manager
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.classifierManager.serviceAccount.annotations | nindent 4 }}
{{ if .Values.agent.managementCluster }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sveltos-agent-manager
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.sveltosAgentManager.serviceAccount.annotations | nindent 4 }}
{{ end }}
---
{{ if .Values.agent.managementCluster }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drift-detection-manager
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.driftDetectionManager.serviceAccount.annotations | nindent 4 }}
{{ end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shard-controller
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: shard-controller
    app.kubernetes.io/part-of: shard-controller
  {{- include "projectsveltos.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.shardController.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: register-mgmt-cluster
  labels:
  {{- include "projectsveltos.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.registerMgmtCluster.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: techsupport-controller
  labels:
    control-plane: techsupport
  {{- include "projectsveltos.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.techsupportController.serviceAccount.annotations | nindent 4 }}
