---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ProviderInterface
metadata:
  name: cluster-api-provider-hetzner
spec:
  template: "cluster-api-provider-hetzner-0-3-0"
  clusterGVKs:
    - group: infrastructure.cluster.x-k8s.io
      version: v1beta1
      kind: HetznerCluster
  clusterIdentityKinds:
    - Secret
  description: "Hetzner infrastructure provider for Cluster API"
