---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ProviderTemplate
metadata:
  name: cluster-api-provider-hetzner-0-3-0
spec:
  helm:
    chartSpec:
      chart: cluster-api-provider-hetzner
      version: 0.3.0
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: oot-repo
