annotations:
  hmc.mirantis.com/infrastructure-providers: azure
apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Cluster API provider Azure
name: cluster-api-provider-azure
type: application
version: 0.0.1
