apiVersion: v2
appVersion: 0.52.2
dependencies:
- name: sveltos-crds
  repository: https://projectsveltos.github.io/helm-charts
  version: 0.52.2
- name: projectsveltos
  repository: https://projectsveltos.github.io/helm-charts
  version: 0.52.2
description: A Helm chart to refer the official projectsveltos helm chart
name: projectsveltos
type: application
version: 0.52.2
