apiVersion: hmc.mirantis.com/v1alpha1
kind: ProviderTemplate
metadata:
  name: k0smotron-0-0-4
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: k0smotron
      version: 0.0.4
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: hmc-templates
