annotations:
  cluster.x-k8s.io/bootstrap-k0sproject-k0smotron: v1beta1
  cluster.x-k8s.io/control-plane-k0sproject-k0smotron: v1beta1
  cluster.x-k8s.io/infrastructure-azure: v1beta1
  cluster.x-k8s.io/provider: infrastructure-azure, control-plane-k0sproject-k0smotron,
    bootstrap-k0sproject-k0smotron
apiVersion: v2
appVersion: v1.32.3+k0s.0
description: 'A KCM template to deploy a k0s cluster on Azure with bootstrapped control
  plane nodes. '
name: azure-standalone-cp
type: application
version: 1.0.0
