apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: {{ include "k0sworkerconfigtemplate.name" . }}
spec:
  template:
    spec:
      version: {{ .Values.k0s.version }}
      args:
      - --enable-cloud-provider
      - --kubelet-extra-args="--cloud-provider=external"
      files:
        - path: "/etc/kubernetes/azure.json"
          permissions: "0644"
          contentFrom:
            secretRef:
              key: worker-node-azure.json
              name: {{ include "azuremachinetemplate.worker.name" . }}-azure-json
