{{- if and .Values.config.secret.create .Values.config.secret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.secret.name }}
  namespace: {{ .Values.config.namespace | default .Release.Namespace | trunc 63 }}
stringData:
{{ toYaml .Values.config.secret.data | indent 2 }}
{{- end }}
