apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0sControlPlane
metadata:
  name: {{ include "k0scontrolplane.name" . }}
  namespace: {{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}
spec:
  replicas: {{ .Values.controlPlaneNumber }}
  version: {{ .Values.k0s.version }}
  k0sConfigSpec:
    files:
      - path: /etc/resolv.conf
        content: |
          nameserver 1.1.1.1
          nameserver 1.0.0.1
          nameserver 2606:4700:4700::1111
        permissions: "0744"
    preStartCommands:
      - systemctl disable --now systemd-resolved
      - systemctl mask --now systemd-resolved
      - sed -i '/swap/d' /etc/fstab
      - swapoff -a
      - snap list | awk '!/^Name|^core|^snapd|^lxd/ {print $1}' | xargs -r snap remove --purge || true
      - snap list | awk '/^lxd/ {print $1}' | xargs -r snap remove --purge || true
      - snap list | awk '/^core/ {print $1}' | xargs -r snap remove --purge || true
      - snap list | awk '/^snapd/ {print $1}' | xargs -r snap remove --purge || true
      - snap list | awk '!/^Name/ {print $1}' | xargs -r snap remove --purge || true
      - apt-get -y remove --purge lxd lxd-agent-loader lxd-installer snapd || true
      - apt-get -y autoremove && apt-get -y clean all
    args:
      - --enable-worker
      - --enable-cloud-provider
      - --kubelet-extra-args="--cloud-provider=external"
      - --disable-components=konnectivity-server
      - --no-taints
    k0s:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s
      spec:
        telemetry:
          enabled: {{ .Values.k0s.telemetry.enabled }}
        api:
          extraArgs:
            anonymous-auth: "true"
            kubelet-preferred-address-types: "ExternalIP,Hostname,InternalDNS,ExternalDNS"
        network:
          provider: calico
          calico:
            mode: vxlan
        extensions:
          helm:
            repositories:
              - name: hcloud
                url: https://charts.hetzner.cloud
            charts:
              - name: hccm
                chartname: hcloud/hcloud-cloud-controller-manager
                namespace: kube-system
                version: {{ .Values.ccm.version }}
                order: 1
                values: |
                  env:
                    HCLOUD_TOKEN:
                      valueFrom:
                        secretKeyRef:
                          name: hetzner-config
                          key: hcloud
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: HCloudMachineTemplate
      name: {{ include "hcloudmachinetemplate.controlplane.name" . }}
      namespace: {{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}
