apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ include "machinedeployment.name" . }}
  namespace: {{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}
  labels:
    nodepool: {{ include "machinedeployment.name" . }}
spec:
  clusterName: {{ include "cluster.name" . }}
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ include "cluster.name" . }}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ include "cluster.name" . }}
        nodepool: {{ include "machinedeployment.name" . }}
    spec:
      version: {{ regexReplaceAll "\\+k0s.+$" .Values.k0s.version "" }}
      clusterName: {{ include "cluster.name" . }}
      failureDomain: {{ .Values.region }}
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: K0sWorkerConfigTemplate
          name: {{ include "k0sworkerconfigtemplate.name" . }}
          namespace: {{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: {{ include "hcloudmachinetemplate.worker.name" . }}
        namespace: {{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}
