annotations:
  hmc.mirantis.com/bootstrap-providers: k0s
  hmc.mirantis.com/control-plane-providers: k0s
  hmc.mirantis.com/infrastructure-providers: azure
apiVersion: v2
appVersion: 1.30.4+k0s.0
description: 'An HMC template to deploy a k8s cluster on Azure with control plane
  components within the management cluster. '
name: azure-hosted-cp
type: application
version: 0.0.1
