annotations:
  cluster.x-k8s.io/provider: infrastructure-kubevirt
  cluster.x-k8s.io/v1beta1: v1beta1
apiVersion: v2
appVersion: 0.1.9
dependencies:
- name: kubevirt
  repository: oci://ghcr.io/k0rdent-oot/oot/charts
  version: '>=0.3.0'
description: A Helm chart for Cluster API provider KubeVirt
name: cluster-api-provider-kubevirt
type: application
version: 0.3.0
