annotations:
  hmc.mirantis.com/bootstrap-providers: eks
  hmc.mirantis.com/controlplane-providers: eks
  hmc.mirantis.com/infrastructure-providers: aws
apiVersion: v2
appVersion: 2.6.1
description: A Helm chart for Cluster API provider AWS
name: cluster-api-provider-aws
type: application
version: 0.0.2
