annotations:
  hmc.mirantis.com/infrastructure-providers: vsphere
  hmc.mirantis.com/type: provider
apiVersion: v2
appVersion: 1.11.0
description: A Helm chart for Cluster API provider vSphere
name: cluster-api-provider-vsphere
type: application
version: 0.0.1
