apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: {{ include "k0smotroncontrolplane.name" . }}
spec:
  replicas: 3
  # dirty hack
  version: {{ .Values.k0s.version | replace "+" "-" }}
  {{- with .Values.k0smotron.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  controllerPlaneFlags:
  - "--enable-cloud-provider=true"
  - "--debug=true"
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: k0s
    spec:
      network:
        provider: calico
        calico:
          mode: ipip
      extensions:
        helm:
          repositories:
          - name: aws-cloud-controller-manager
            url: https://kubernetes.github.io/cloud-provider-aws
          - name: aws-ebs-csi-driver
            url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
          charts:
          - name: aws-cloud-controller-manager
            namespace: kube-system
            chartname: aws-cloud-controller-manager/aws-cloud-controller-manager
            version: "0.0.8"
            values: |
              image:
                tag: v1.30.3
              args:
                - --v=2
                - --cloud-provider=aws
                - --cluster-cidr={{ first .Values.clusterNetwork.pods.cidrBlocks }}
                - --allocate-node-cidrs=true
                - --cluster-name={{ include "cluster.name" . }}
              # Removing the default `node-role.kubernetes.io/control-plane` node selector
              # TODO: it does not work
              nodeSelector:
                node-role.kubernetes.io/control-plane: null
          - name: aws-ebs-csi-driver
            namespace: kube-system
            chartname: aws-ebs-csi-driver/aws-ebs-csi-driver
            version: 2.33.0
            values: |
              defaultStorageClass:
                enabled: true
              node:
                kubeletPath: /var/lib/k0s/kubelet
