annotations:
  cluster.x-k8s.io/provider: infrastructure-hetzner
  cluster.x-k8s.io/v1beta1: v1beta1
apiVersion: v2
appVersion: 1.0.3
description: A Helm chart for Cluster API Provider Hetzner
name: cluster-api-provider-hetzner
type: application
version: 0.3.0
