apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: {{ include "hcloudmachinetemplate.controlplane.name" . }}
  namespace: {{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}
spec:
  template:
    spec:
      imageName: {{ .Values.controlPlane.imageName }}
      placementGroupName: control-plane
      type: {{ .Values.controlPlane.type }}
