apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerCluster
metadata:
  name: {{ include "cluster.name" . }}
  namespace: {{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}
spec:
  controlPlaneEndpoint:
    host: ""
    port: 6443
  controlPlaneLoadBalancer:
    region: {{ .Values.region }}
  controlPlaneRegions:
    - {{ .Values.region }}
  hcloudPlacementGroups:
    - name: control-plane
      type: spread
    - name: worker
      type: spread
  hetznerSecretRef:
    key:
      hcloudToken: hcloud
    name: hetzner-config
  sshKeys:
    hcloud:
      - name: {{ .Values.sshkey.name }}
