apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: K0sWorkerConfigTemplate
metadata:
  name: {{ include "k0sworkerconfigtemplate.name" . }}
  namespace: {{ .Values.cluster.namespace | default .Release.Namespace | trunc 63 }}
spec:
  template:
    spec:
      version: {{ .Values.k0s.version }}
      files:
        - path: /etc/resolv.conf
          content: |
            nameserver 1.1.1.1
            nameserver 1.0.0.1
            nameserver 2606:4700:4700::1111
          permissions: "0744"
      preStartCommands:
        - systemctl disable --now systemd-resolved
        - systemctl mask --now systemd-resolved
        - sed -i '/swap/d' /etc/fstab
        - swapoff -a
        - snap list | awk '!/^Name|^core|^snapd|^lxd/ {print $1}' | xargs -r snap remove --purge || true
        - snap list | awk '/^lxd/ {print $1}' | xargs -r snap remove --purge || true
        - snap list | awk '/^core/ {print $1}' | xargs -r snap remove --purge || true
        - snap list | awk '/^snapd/ {print $1}' | xargs -r snap remove --purge || true
        - snap list | awk '!/^Name/ {print $1}' | xargs -r snap remove --purge || true
        - apt-get -y remove --purge lxd lxd-agent-loader lxd-installer snapd || true
        - apt-get -y autoremove && apt-get -y clean all
      args:
        - --enable-cloud-provider
        - --kubelet-extra-args="--cloud-provider=external"
