---
apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ProviderInterface
metadata:
  name: cluster-api-provider-kubevirt
spec:
  template: "cluster-api-provider-kubevirt-0-3-0"
  clusterGVKs:
    - group: infrastructure.cluster.x-k8s.io
      version: v1alpha1
      kind: KubevirtCluster
  clusterIdentityKinds:
    - Secret
  description: "KubeVirt infrastructure provider for Cluster API"
