apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: k0smotron
spec:
  version: v1.0.4
  fetchConfig:
    url: https://github.com/k0sproject/k0smotron/releases/{{ .Values.version }}/infrastructure-components.yaml
  {{- if .Values.configSecret.name }}
  configSecret:
    name: {{ .Values.configSecret.name }}
    namespace: {{ .Values.configSecret.namespace | default .Release.Namespace | trunc 63 }}
  {{- end }}
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: BootstrapProvider
metadata:
  name: k0smotron
spec:
  version: v1.0.4
  fetchConfig:
    url: https://github.com/k0sproject/k0smotron/releases/{{ .Values.version }}/bootstrap-components.yaml
  {{- if .Values.configSecret.name }}
  configSecret:
    name: {{ .Values.configSecret.name }}
    namespace: {{ .Values.configSecret.namespace | default .Release.Namespace | trunc 63 }}
  {{- end }}
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: k0smotron
spec:
  version: v1.0.4
  fetchConfig:
    url: https://github.com/k0sproject/k0smotron/releases/{{ .Values.version }}/control-plane-components.yaml
  {{- if .Values.configSecret.name }}
  configSecret:
    name: {{ .Values.configSecret.name }}
    namespace: {{ .Values.configSecret.namespace | default .Release.Namespace | trunc 63 }}
  {{- end }}
