name: Backup Helm Charts

on:
  schedule:
    - cron: '0 1 * * *' # Daily at 1:00 AM UTC
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode (no actual changes)'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  backup-charts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Add repos
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update

      - name: Install utils
        run: sudo apt-get install -y jq gh

      - name: Run backup script
        env:
          # https://github.com/settings/tokens
          GH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
        run: |
          if [ "${{ inputs.dry_run }}" = "true" ]; then
            ./scripts/backup-charts.sh --dry-run --gh-orgs "k0rdent,k0rdent-oot"
          else
            ./scripts/backup-charts.sh --gh-orgs "k0rdent,k0rdent-oot"
          fi

      - name: Commit and push changes
        if: inputs.dry_run == 'false'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Snapshot-$(date +%s)"
            git push
          else
            echo "No changes to commit"
          fi
